/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Logic.SportsLeague;
import Logic.Team;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author faisa
 */
public class Edit_Team extends javax.swing.JFrame {

    /**
     * Creates new form Edit_Team
     */
    
    private Team edit_team_obj;
   
     public Edit_Team() {
        initComponents();
    }
    
    public Edit_Team(Team edit_team) {
        initComponents();
        tNameTxt.setText(edit_team.getName());
        stadiumTxt.setText(edit_team.getStadium());
        stadiumCapacityTxt.setText(String.valueOf( (int) edit_team.getCapacity()));
        this.edit_team_obj=edit_team;
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editTeamDetailsPanel = new javax.swing.JPanel();
        editTeamDetailsLabel = new javax.swing.JLabel();
        editTeamDetailsInputPanel = new javax.swing.JPanel();
        Field = new javax.swing.JPanel();
        Field1 = new javax.swing.JPanel();
        tNameLabel = new javax.swing.JLabel();
        tNameTxt = new javax.swing.JTextField();
        Field2 = new javax.swing.JPanel();
        Field3 = new javax.swing.JPanel();
        stadiumLabel = new javax.swing.JLabel();
        stadiumTxt = new javax.swing.JTextField();
        Field4 = new javax.swing.JPanel();
        Field5 = new javax.swing.JPanel();
        stadiumCapacityLabel = new javax.swing.JLabel();
        Field7 = new javax.swing.JPanel();
        Field6 = new javax.swing.JPanel();
        goBackBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        stadiumCapacityTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editTeamDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));

        editTeamDetailsLabel.setBackground(new java.awt.Color(255, 255, 255));
        editTeamDetailsLabel.setFont(new java.awt.Font("Gadugi", 0, 90)); // NOI18N
        editTeamDetailsLabel.setForeground(new java.awt.Color(0, 127, 255));
        editTeamDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editTeamDetailsLabel.setText("Edit Team Details");
        editTeamDetailsLabel.setToolTipText("");
        editTeamDetailsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        editTeamDetailsInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        editTeamDetailsInputPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 127, 255), 10, true));

        Field.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout FieldLayout = new javax.swing.GroupLayout(Field);
        Field.setLayout(FieldLayout);
        FieldLayout.setHorizontalGroup(
            FieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
        );
        FieldLayout.setVerticalGroup(
            FieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        Field1.setBackground(new java.awt.Color(255, 255, 255));

        tNameLabel.setFont(new java.awt.Font("Gadugi", 0, 36)); // NOI18N
        tNameLabel.setForeground(new java.awt.Color(0, 127, 255));
        tNameLabel.setText("Enter Team Name:");

        javax.swing.GroupLayout Field1Layout = new javax.swing.GroupLayout(Field1);
        Field1.setLayout(Field1Layout);
        Field1Layout.setHorizontalGroup(
            Field1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Field1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(tNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(tNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Field1Layout.setVerticalGroup(
            Field1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Field1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Field1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Field1Layout.createSequentialGroup()
                        .addComponent(tNameLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tNameTxt)))
        );

        Field2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Field2Layout = new javax.swing.GroupLayout(Field2);
        Field2.setLayout(Field2Layout);
        Field2Layout.setHorizontalGroup(
            Field2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
        );
        Field2Layout.setVerticalGroup(
            Field2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        Field3.setBackground(new java.awt.Color(255, 255, 255));

        stadiumLabel.setFont(new java.awt.Font("Gadugi", 0, 36)); // NOI18N
        stadiumLabel.setForeground(new java.awt.Color(0, 127, 255));
        stadiumLabel.setText("Enter Stadium Name:");

        stadiumTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stadiumTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Field3Layout = new javax.swing.GroupLayout(Field3);
        Field3.setLayout(Field3Layout);
        Field3Layout.setHorizontalGroup(
            Field3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Field3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(stadiumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stadiumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Field3Layout.setVerticalGroup(
            Field3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Field3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(Field3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stadiumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stadiumLabel))
                .addContainerGap())
        );

        Field4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Field4Layout = new javax.swing.GroupLayout(Field4);
        Field4.setLayout(Field4Layout);
        Field4Layout.setHorizontalGroup(
            Field4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Field4Layout.setVerticalGroup(
            Field4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        Field5.setBackground(new java.awt.Color(255, 255, 255));

        stadiumCapacityLabel.setFont(new java.awt.Font("Gadugi", 0, 36)); // NOI18N
        stadiumCapacityLabel.setForeground(new java.awt.Color(0, 127, 255));
        stadiumCapacityLabel.setText("Enter Stadium Capacity:");

        javax.swing.GroupLayout Field5Layout = new javax.swing.GroupLayout(Field5);
        Field5.setLayout(Field5Layout);
        Field5Layout.setHorizontalGroup(
            Field5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Field5Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(stadiumCapacityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Field5Layout.setVerticalGroup(
            Field5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Field5Layout.createSequentialGroup()
                .addComponent(stadiumCapacityLabel)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        Field7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Field7Layout = new javax.swing.GroupLayout(Field7);
        Field7.setLayout(Field7Layout);
        Field7Layout.setHorizontalGroup(
            Field7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        Field7Layout.setVerticalGroup(
            Field7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        Field6.setBackground(new java.awt.Color(255, 255, 255));

        goBackBtn.setBackground(new java.awt.Color(211, 211, 211));
        goBackBtn.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        goBackBtn.setForeground(new java.awt.Color(0, 127, 255));
        goBackBtn.setText("Go Back");
        goBackBtn.setToolTipText("");
        goBackBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 127, 255), 4, true));
        goBackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBackBtn.setPreferredSize(new java.awt.Dimension(231, 51));
        goBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackBtnActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(211, 211, 211));
        saveBtn.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(0, 127, 255));
        saveBtn.setText("Save");
        saveBtn.setToolTipText("");
        saveBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 127, 255), 4, true));
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.setPreferredSize(new java.awt.Dimension(231, 51));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Field6Layout = new javax.swing.GroupLayout(Field6);
        Field6.setLayout(Field6Layout);
        Field6Layout.setHorizontalGroup(
            Field6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Field6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(goBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Field6Layout.setVerticalGroup(
            Field6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Field6Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(Field6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout editTeamDetailsInputPanelLayout = new javax.swing.GroupLayout(editTeamDetailsInputPanel);
        editTeamDetailsInputPanel.setLayout(editTeamDetailsInputPanelLayout);
        editTeamDetailsInputPanelLayout.setHorizontalGroup(
            editTeamDetailsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTeamDetailsInputPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(editTeamDetailsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editTeamDetailsInputPanelLayout.createSequentialGroup()
                        .addComponent(Field5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stadiumCapacityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addComponent(Field6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Field7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Field1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Field2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Field4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(editTeamDetailsInputPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Field3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editTeamDetailsInputPanelLayout.setVerticalGroup(
            editTeamDetailsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTeamDetailsInputPanelLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editTeamDetailsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Field5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stadiumCapacityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(Field6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout editTeamDetailsPanelLayout = new javax.swing.GroupLayout(editTeamDetailsPanel);
        editTeamDetailsPanel.setLayout(editTeamDetailsPanelLayout);
        editTeamDetailsPanelLayout.setHorizontalGroup(
            editTeamDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editTeamDetailsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1181, Short.MAX_VALUE)
            .addGroup(editTeamDetailsPanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(editTeamDetailsInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(113, 113, 113))
        );
        editTeamDetailsPanelLayout.setVerticalGroup(
            editTeamDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTeamDetailsPanelLayout.createSequentialGroup()
                .addComponent(editTeamDetailsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editTeamDetailsInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(470, 470, 470))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1193, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(editTeamDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editTeamDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackBtnActionPerformed
        try {
            // TODO add your handling code here:
            
            Select_Team V = new Select_Team();
            V.setVisible(true);
            this.setVisible(false);
            V.setSize(this.getSize());
        } catch (IOException ex) {
            Logger.getLogger(Edit_Team.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_goBackBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
         SportsLeague sp=null;
        try { 
            sp = new SportsLeague();
        } catch (IOException ex) {
            Logger.getLogger(Edit_Team.class.getName()).log(Level.SEVERE, null, ex);
        }
        sp.editTeamDetails(edit_team_obj,tNameTxt.getText(),stadiumTxt.getText(), Integer.parseInt(stadiumCapacityTxt.getText()));
        File file_edit_tea = new File("teams.txt");
        FileOutputStream fot=null;        
        try {
                     fot = new FileOutputStream(file_edit_tea);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Edit_Player.class.getName()).log(Level.SEVERE, null, ex);
                }
            try {
                ObjectOutputStream oos = new ObjectOutputStream(fot);
                oos.writeObject(sp.getTeams());
            } catch (IOException ex) {
                Logger.getLogger(Edit_Player.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void stadiumTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stadiumTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stadiumTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_Team().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Field;
    private javax.swing.JPanel Field1;
    private javax.swing.JPanel Field2;
    private javax.swing.JPanel Field3;
    private javax.swing.JPanel Field4;
    private javax.swing.JPanel Field5;
    private javax.swing.JPanel Field6;
    private javax.swing.JPanel Field7;
    private javax.swing.JPanel editTeamDetailsInputPanel;
    private javax.swing.JLabel editTeamDetailsLabel;
    private javax.swing.JPanel editTeamDetailsPanel;
    private javax.swing.JButton goBackBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel stadiumCapacityLabel;
    private javax.swing.JTextField stadiumCapacityTxt;
    private javax.swing.JLabel stadiumLabel;
    private javax.swing.JTextField stadiumTxt;
    private javax.swing.JLabel tNameLabel;
    private javax.swing.JTextField tNameTxt;
    // End of variables declaration//GEN-END:variables
}
