/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author salma
 */
public class Select_Team extends javax.swing.JFrame {

    /**
     * Creates new form Select_Team
     */
    public Select_Team() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectTeamPanel = new javax.swing.JPanel();
        selectTeamTitle = new javax.swing.JLabel();
        editTeamPanel = new javax.swing.JPanel();
        goBackBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        selectBtn = new javax.swing.JButton();
        teamLabel = new javax.swing.JLabel();
        teamComboBox = new javax.swing.JComboBox<>();
        chooseTeamLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectTeamPanel.setBackground(new java.awt.Color(255, 255, 255));
        selectTeamPanel.setToolTipText("");

        selectTeamTitle.setBackground(new java.awt.Color(255, 255, 255));
        selectTeamTitle.setFont(new java.awt.Font("Gadugi", 0, 90)); // NOI18N
        selectTeamTitle.setForeground(new java.awt.Color(0, 127, 255));
        selectTeamTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectTeamTitle.setText("Select Team");
        selectTeamTitle.setToolTipText("");
        selectTeamTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        editTeamPanel.setBackground(new java.awt.Color(255, 255, 255));
        editTeamPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 127, 255), 10, true));

        goBackBtn.setBackground(new java.awt.Color(211, 211, 211));
        goBackBtn.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        goBackBtn.setForeground(new java.awt.Color(0, 127, 255));
        goBackBtn.setText("Go Back");
        goBackBtn.setToolTipText("");
        goBackBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 127, 255), 4, true));
        goBackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBackBtn.setPreferredSize(new java.awt.Dimension(231, 51));
        goBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        selectBtn.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        selectBtn.setForeground(new java.awt.Color(0, 127, 255));
        selectBtn.setText("Select Team");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(selectBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(selectBtn)
                .addGap(0, 158, Short.MAX_VALUE))
        );

        teamLabel.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        teamLabel.setForeground(new java.awt.Color(0, 127, 255));
        teamLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        teamLabel.setText("Select Team :");

        teamComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        teamComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamComboBoxActionPerformed(evt);
            }
        });

        chooseTeamLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        chooseTeamLabel.setForeground(new java.awt.Color(0, 127, 255));
        chooseTeamLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chooseTeamLabel.setText("Choose Team to edit");

        javax.swing.GroupLayout editTeamPanelLayout = new javax.swing.GroupLayout(editTeamPanel);
        editTeamPanel.setLayout(editTeamPanelLayout);
        editTeamPanelLayout.setHorizontalGroup(
            editTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTeamPanelLayout.createSequentialGroup()
                .addGroup(editTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editTeamPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(goBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editTeamPanelLayout.createSequentialGroup()
                            .addContainerGap(286, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(editTeamPanelLayout.createSequentialGroup()
                            .addGap(131, 131, 131)
                            .addComponent(teamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(teamComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(44, 44, 44))))
                .addGap(123, 123, 123))
            .addGroup(editTeamPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(chooseTeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editTeamPanelLayout.setVerticalGroup(
            editTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTeamPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(chooseTeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(editTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(goBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout selectTeamPanelLayout = new javax.swing.GroupLayout(selectTeamPanel);
        selectTeamPanel.setLayout(selectTeamPanelLayout);
        selectTeamPanelLayout.setHorizontalGroup(
            selectTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selectTeamTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
            .addGroup(selectTeamPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(editTeamPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        selectTeamPanelLayout.setVerticalGroup(
            selectTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectTeamPanelLayout.createSequentialGroup()
                .addComponent(selectTeamTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editTeamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(343, 343, 343))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 983, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(selectTeamPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1129, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectTeamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackBtnActionPerformed
        // TODO add your handling code here:
        
        Manage_Teams V = new Manage_Teams();
        V.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_goBackBtnActionPerformed

    private void teamComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamComboBoxActionPerformed

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        // TODO add your handling code here:
        
        Edit_Team V = new Edit_Team();
        V.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_selectBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Select_Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Select_Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Select_Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Select_Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Select_Team().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chooseTeamLabel;
    private javax.swing.JPanel editTeamPanel;
    private javax.swing.JButton goBackBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton selectBtn;
    private javax.swing.JPanel selectTeamPanel;
    private javax.swing.JLabel selectTeamTitle;
    private javax.swing.JComboBox<String> teamComboBox;
    private javax.swing.JLabel teamLabel;
    // End of variables declaration//GEN-END:variables
}
